# Generated by Django 5.2.8 on 2025-11-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='is_complete',
            new_name='is_completed',
        ),
    ]
