# Generated by Django 5.2.8 on 2025-11-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_is_complete_tasks_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdetail',
            old_name='assgned_to',
            new_name='assigned_to',
        ),
    ]
