# Generated by Django 5.2.8 on 2025-11-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_assgned_to_taskdetail_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='assigned_to',
            field=models.ManyToManyField(related_name='tasks', to='tasks.employee'),
        ),
    ]
